### ISSUE TITLE
Build fails with NullPointerException

### ISSUE THREAD

**Issue by arvl130** [ReilySiegel/bear#1]
I am trying to build this package with OpenJDK 8 and GraalVM on Arch Linux, but I'm getting this this output:
```
➜ clojure -A:native-image
Compiling reilysiegel.bear
Execution error (NullPointerException) at java.lang.ProcessBuilder/start (ProcessBuilder.java:1012).
null

Full report at:
/tmp/clojure-5206517164125988165.edn
```
Here is the log mentioned in the error: [clojure-5206517164125988165.edn](https://gist.github.com/arvl130/4a240fcebee4c21c6cfbbf79d1160861)

**Comment by ReilySiegel** [comment]
Did you set GraalVM as your active java version with `$ sudo archlinux-java set java-11-graalvm`? I can reproduce the same error using OpenJDK instead of GraalVM. Looks like an upstream dep fails with that exception when the native-image binary is not found.

**Comment by ReilySiegel** [comment]
This package is now available on the AUR as `reilysiegel-bear-git`. Hopefully this makes installation easier, as GraalVM (and Java in general) can be a pain on Arch.
